import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, cpSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { git, context } from '../core/actions.mjs';
import { digest } from '../core/scope.mjs';
import { reviewPlan, inspectReview } from '../core/review.mjs';
import { reviewBundle } from '../core/economy.mjs';
import { runVerification, verificationPlan } from '../core/verification.mjs';
const root = fileURLToPath(new URL('..', import.meta.url));
const proof = 'sha256:' + 'b'.repeat(64);

test('committed review binds local policy/full leaves and real behavior without claiming intent success', () => {
  const cwd = mkdtempSync(join(root, '.review-proof-'));
  try {
    git(cwd, 'init', '--initial-branch=feature/7-small');
    git(cwd, 'remote', 'add', 'origin', 'https://github.com/ExampleOrg/sample.git');
    mkdirSync(join(cwd, '.governance'));
    for (const name of ['core', 'skills', 'templates', 'policy.md', 'quality.md', 'principles.md', 'config.json']) cpSync(join(root, name), join(cwd, '.governance', name), { recursive: true });
    const { delivery } = JSON.parse(readFileSync(join(root, 'examples/adapter.json')));
    writeFileSync(join(cwd, '.governance/delivery.json'), JSON.stringify(delivery));
    writeFileSync(join(cwd, '.governance/project.json'), JSON.stringify(delivery.project));
    writeFileSync(join(cwd, 'AGENTS.md'), '# Existing stronger project policy\nNo external writes without approval.\n');
    writeFileSync(join(cwd, 'value.cjs'), 'module.exports = 1;\n');
    writeFileSync(join(cwd, '.gitignore'), '.governance-artifacts/\n');
    writeFileSync(join(cwd, '.governance/verification.json'), JSON.stringify({ schemaVersion: 1, commands: { value: ['node', '-e', 'require("node:assert/strict").equal(require("./value.cjs"), 2)'] } }));
    const commit = () => { git(cwd, 'add', '.'); git(cwd, '-c', 'core.hooksPath=/dev/null', '-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.test', 'commit', '-m', 'fixture'); return git(cwd, 'rev-parse', 'HEAD'); };
    const base = commit();
    const scope = { version: 1, revision: 1, intent: 'Return two to the caller', intentSource: 'issue:7', boundaries: 'value.cjs only', source: { ref: 'feature/7-small', sha: base }, criteria: [{ id: 'VALUE', outcome: 'Returns exactly 2', method: 'Execute caller assertion' }] };
    assert.equal(runVerification({ cwd, scope, project: delivery.project, check: 'value' }).code, 1);
    writeFileSync(join(cwd, 'value.cjs'), 'module.exports = 2;\n');
    const head = commit(); context(cwd, delivery);
    const plan = reviewPlan({ cwd, scope, head, reviewBase: base, stagingBase: base, delivery });
    assert.deepEqual([plan.required, plan.sizeTrigger, plan.policyChanged, plan.review.total, plan.policy.items.length], [true, false, false, 2, 39]);
    assert.equal(plan.policy.items.filter(x => x.conditional).length, 23);
    assert.equal(inspectReview(plan, null, scope).ready, false);
    const record = { version: 1, planDigest: plan.digest, scopeDigest: digest(scope), reviewer: 'lead', reviewedAt: '2026-09-15T00:00:00Z', conditions: plan.policy.items.map(x => ({ id: x.id, disposition: 'satisfied', proof })), criteria: [{ id: 'VALUE', proof }], intentProof: proof, size: { kind: 'feature', decision: 'within-trigger', proof: null } };
    assert.equal(inspectReview(plan, record, scope).ready, true);
    const missing = structuredClone(record); missing.intentProof = null;
    assert.equal(inspectReview(plan, missing, scope).ready, false);
    missing.intentProof = proof; missing.conditions = missing.conditions.filter(x => x.id !== 'principle:project-policy');
    assert.equal(inspectReview(plan, missing, scope).ready, false);
    const passed = runVerification({ cwd, scope: { ...scope, source: { ...scope.source, sha: head } }, project: delivery.project, check: 'value' });
    assert.deepEqual([passed.code, passed.exit, passed.outputRetained], [0, 0, false]); assert.match(passed.acceptance, /^unverified/u);
    assert.throws(() => runVerification({ cwd, scope: { ...scope, source: { ...scope.source, sha: head } }, project: delivery.project, check: 'unknown' }));
    mkdirSync(join(cwd, '.governance-artifacts'));
    writeFileSync(join(cwd, '.governance-artifacts/usage.json'), JSON.stringify({ version: 1, scopeDigest: digest(scope), complete: false, entries: [] }));
    const packet = reviewBundle(context(cwd, delivery), scope, { head, base, staging: base, output: '.governance-artifacts/review.json' }, { context: ['value.cjs'], principles: ['principle-prove-it-works'.replace('principle-', 'principle:')], checks: [{ name: 'value', criteria: ['VALUE'] }], ledger: '.governance-artifacts/usage.json', reasoning: { effort: 'medium', reason: null } });
    assert.equal(packet.code, 0);
    const bundle = JSON.parse(readFileSync(join(cwd, packet.result.artifact.path)));
    assert.equal(bundle.checks[0].exit, 0); assert.equal(bundle.criteria[0].acceptance, 'lead-verification-required');
    assert.equal(bundle.costs.total, null); assert.equal(bundle.metadata.base, 'develop');
    assert.ok(bundle.context['.governance/quality.md'].includes('### Additional code-quality review conditions'));
    assert.ok(bundle.context['.governance/skills/principle-prove-it-works/SKILL.md'].includes('# Prove It Works'));
    writeFileSync(join(cwd, 'AGENTS.md'), '# Changed project policy\n');
    const changed = commit(), changedPlan = reviewPlan({ cwd, scope, head: changed, reviewBase: base, stagingBase: base, delivery });
    assert.equal(changedPlan.policyChanged, true); assert.equal(inspectReview(changedPlan, record, scope).ready, false);
    writeFileSync(join(cwd, '.governance/verification.json'), '{"schemaVersion":1,"commands":{}}\n');
    assert.deepEqual(verificationPlan({ cwd, base, head: commit(), scope }).unresolved, ['project-verification-unconfigured', 'verification-policy-changed']);
  } finally { rmSync(cwd, { recursive: true, force: true }); }
});
